name: clustr
channels:
- defaults
dependencies:
- astropy=4.0
- matplotlib=3.1.3
- pip=20.0.2
- python=3.7.6
- r-essentials=3.6.0
- rpy2=2.9.4
- scipy=1.4.1
- pip:
  - corner==2.0.1
  - pypdf2==1.26.0
  - "git+https://github.com/jmeyers314/linmix.git"
